# Package Overview
package_name: bank_churn_model

# Data Files
training_data_file: BankChurners.csv

# Variables
# The variable we are attempting to predict (Attrition_Flag)
target: Attrition_Flag

pipeline_name: bank_churn_model
pipeline_save_file: bank_churn_model_output_v

# Features that will go inside the processing pipeline
features:
  - Customer_Age
  - Gender
  - Dependent_count
  - Education_Level
  - Marital_Status
  - Income_Category
  - Card_Category
  - Months_on_book
  - Total_Relationship_Count
  - Months_Inactive_12_mon
  - Contacts_Count_12_mon
  - Credit_Limit
  - Total_Revolving_Bal
  - Avg_Open_To_Buy
  - Total_Amt_Chng_Q4_Q1
  - Total_Trans_Amt
  - Total_Trans_Ct
  - Total_Ct_Chng_Q4_Q1
  - Avg_Utilization_Ratio

# Unused fields
unused_fields: 
  - CLIENTNUM

# Feature names
Customer_Age_var: Customer_Age
Gender_var: Gender
Dependent_count_var: Dependent_count
Education_Level_var: Education_Level
Marital_Status_var: Marital_Status
Income_Category_var: Income_Category
Card_Category_var: Card_Category
Months_on_book_var: Months_on_book
Total_Relationship_Count_var: Total_Relationship_Count
Months_Inactive_12_mon_var: Months_Inactive_12_mon
Contacts_Count_12_mon_var: Contacts_Count_12_mon
Credit_Limit_var: Credit_Limit
Total_Revolving_Bal_var: Total_Revolving_Bal
Avg_Open_To_Buy_var: Avg_Open_To_Buy
Total_Amt_Chng_Q4_Q1_var: Total_Amt_Chng_Q4_Q1
Total_Trans_Amt_var: Total_Trans_Amt
Total_Trans_Ct_var: Total_Trans_Ct
Total_Ct_Chng_Q4_Q1_var: Total_Ct_Chng_Q4_Q1
Avg_Utilization_Ratio_var: Avg_Utilization_Ratio

# Set train/test split
test_size: 0.20

# Set the random seed
random_state: 42

# Algorithm parameters
# Random Forest parameters
rf_n_estimators: 200
rf_max_depth: 10

# CatBoost parameters
cat_iterations: 200
