name: CD Pipeline

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: sudo docker pull amba1178/bank-fastapi:latest
      - name: Delete Old Docker Container
        run: sudo docker rm -f bank-fastapi-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name bank-fastapi-container amba1178/bank-fastapi
